export default function Head() {
  return (
    <>
      <title>Celina&aposs Portflio</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="generated by celina" />
      <link rel="icon" href="" />
    </>
  );
}
